### ISSUE TITLE
Map container not found.

### ISSUE THREAD

**Issue by saikumarnagumantri** [MapmyIndia/mapmyindia-map-cordova-ionic-beta#1]
Map container not found.

**Comment by kunalbharti** [comment]
@saikumarnagumantri Please elaborate your query. 
---from what I understand---
You need to define a 'div' ID and then pass it to `loadmap` method.
See https://github.com/MapmyIndia/mapmyindia-map-cordova-ionic-beta#1-mapload
---end---

**Comment by pgmoorthy1411** [comment]
Map container not found. mymapindia in ionic
how sole this
